"""add link tracking fields to extracted_docs

Revision ID: 09301483fcde
Revises: e07e5ca85c4e
Create Date: 2025-11-04 12:36:20.886542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09301483fcde'
down_revision: Union[str, Sequence[str], None] = 'e07e5ca85c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_docs', sa.Column('is_linked', sa.Boolean(), nullable=True))
    op.add_column('extracted_docs', sa.Column('link_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_docs', 'link_reason')
    op.drop_column('extracted_docs', 'is_linked')
    # ### end Alembic commands ###
