"""Final cleanup of ExtractedDocs and relationship fix

Revision ID: a8d2c85f5068
Revises: ba37ce71432f
Create Date: 2025-11-05 11:39:00.851653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d2c85f5068'
down_revision: Union[str, Sequence[str], None] = 'ba37ce71432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
