"""Simplify ExtractedDocs model and add essential fields

Revision ID: ba37ce71432f
Revises: 09301483fcde
Create Date: 2025-11-05 11:22:38.933623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba37ce71432f'
down_revision: Union[str, Sequence[str], None] = '09301483fcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_docs', sa.Column('principal_company', sa.String(length=255), nullable=True))
    op.add_column('extracted_docs', sa.Column('origin', sa.String(length=255), nullable=True))
    op.add_column('extracted_docs', sa.Column('destination', sa.String(length=255), nullable=True))
    op.add_column('extracted_docs', sa.Column('order_type', sa.String(length=50), nullable=True))
    op.add_column('extracted_docs', sa.Column('acknowledgement_status', sa.String(length=50), nullable=True))
    op.alter_column('extracted_docs', 'upload_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('extracted_docs', 'doc_category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'invoice_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'lr_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'raw_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'validation_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'last_validated_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('extracted_docs_upload_id_fkey'), 'extracted_docs', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_docs', 'upload_metadata', ['upload_id'], ['id'])
    op.drop_column('extracted_docs', 'consignee')
    op.drop_column('extracted_docs', 'gross_weight')
    op.drop_column('extracted_docs', 'created_at')
    op.drop_column('extracted_docs', 'net_weight')
    op.drop_column('extracted_docs', 'extraction_confidence')
    op.drop_column('extracted_docs', 'stamp_detected')
    op.drop_column('extracted_docs', 'is_flagged')
    op.drop_column('extracted_docs', 'total_amount')
    op.drop_column('extracted_docs', 'consignor')
    op.drop_column('extracted_docs', 'quantity')
    op.drop_column('extracted_docs', 'signature_detected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_docs', sa.Column('signature_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('consignor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('stamp_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('extraction_confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('net_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('gross_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('extracted_docs', sa.Column('consignee', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'extracted_docs', type_='foreignkey')
    op.create_foreign_key(op.f('extracted_docs_upload_id_fkey'), 'extracted_docs', 'upload_metadata', ['upload_id'], ['id'], ondelete='CASCADE')
    op.alter_column('extracted_docs', 'last_validated_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'validation_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'raw_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'lr_no',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'invoice_no',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'doc_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('extracted_docs', 'upload_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('extracted_docs', 'acknowledgement_status')
    op.drop_column('extracted_docs', 'order_type')
    op.drop_column('extracted_docs', 'destination')
    op.drop_column('extracted_docs', 'origin')
    op.drop_column('extracted_docs', 'principal_company')
    # ### end Alembic commands ###
