"""initial schema

Revision ID: e07e5ca85c4e
Revises: 
Create Date: 2025-11-04 11:42:07.889993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07e5ca85c4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=50), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('truck_no', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_trips_id'), 'linked_trips', ['id'], unique=False)
    op.create_index(op.f('ix_linked_trips_trip_id'), 'linked_trips', ['trip_id'], unique=True)
    op.create_table('upload_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.String(length=30), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('detected_dealer', sa.String(length=100), nullable=True),
    sa.Column('detected_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_upload_metadata_id'), 'upload_metadata', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dealer_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_name', sa.String(), nullable=False),
    sa.Column('bill_no', sa.String(), nullable=True),
    sa.Column('duration_from', sa.Date(), nullable=True),
    sa.Column('duration_to', sa.Date(), nullable=True),
    sa.Column('total_lr_count', sa.Integer(), nullable=True),
    sa.Column('total_truck_count', sa.Integer(), nullable=True),
    sa.Column('total_net_weight', sa.Float(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_summary_id'), 'dealer_summary', ['id'], unique=False)
    op.create_table('extracted_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('doc_category', sa.String(length=30), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('lr_no', sa.String(length=100), nullable=True),
    sa.Column('lr_date', sa.DateTime(), nullable=True),
    sa.Column('truck_no', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('consignor', sa.String(length=255), nullable=True),
    sa.Column('consignee', sa.String(length=255), nullable=True),
    sa.Column('bill_to_party', sa.String(length=255), nullable=True),
    sa.Column('ship_to_party', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('stamp_detected', sa.Boolean(), nullable=True),
    sa.Column('signature_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_validated_by', sa.String(length=100), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_docs_id'), 'extracted_docs', ['id'], unique=False)
    op.create_table('extracted_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('dealer_name', sa.String(), nullable=True),
    sa.Column('bill_no', sa.String(), nullable=True),
    sa.Column('duration_from', sa.Date(), nullable=True),
    sa.Column('duration_to', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('lr_no', sa.String(), nullable=True),
    sa.Column('lr_date', sa.Date(), nullable=True),
    sa.Column('truck_no', sa.String(), nullable=True),
    sa.Column('bill_to_party', sa.String(), nullable=True),
    sa.Column('ship_to_party', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_pages_id'), 'extracted_pages', ['id'], unique=False)
    op.create_table('trip_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('doc_role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['extracted_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['linked_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_documents_id'), 'trip_documents', ['id'], unique=False)
    op.create_table('weighment_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tare_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('slip_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['extracted_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weighment_slips_id'), 'weighment_slips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weighment_slips_id'), table_name='weighment_slips')
    op.drop_table('weighment_slips')
    op.drop_index(op.f('ix_trip_documents_id'), table_name='trip_documents')
    op.drop_table('trip_documents')
    op.drop_index(op.f('ix_extracted_pages_id'), table_name='extracted_pages')
    op.drop_table('extracted_pages')
    op.drop_index(op.f('ix_extracted_docs_id'), table_name='extracted_docs')
    op.drop_table('extracted_docs')
    op.drop_index(op.f('ix_dealer_summary_id'), table_name='dealer_summary')
    op.drop_table('dealer_summary')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upload_metadata_id'), table_name='upload_metadata')
    op.drop_table('upload_metadata')
    op.drop_index(op.f('ix_linked_trips_trip_id'), table_name='linked_trips')
    op.drop_index(op.f('ix_linked_trips_id'), table_name='linked_trips')
    op.drop_table('linked_trips')
    # ### end Alembic commands ###
